name: tarot_app
description: Mobile app for helping with reading and interpretation of Tarot with AI.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.5.3'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/cards/
  fonts:
    - family: AlexBrush
      fonts:
        - asset: assets/fonts/AlexBrush-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 800